import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { parseIcon, readIconSource, renderIconMap, toPathD } from "./icons-source.mjs";

test("toPathD turns the shapes an icon set uses into path data", () => {
  assert.equal(toPathD("rect", { x: "3", y: "3", width: "18", height: "18" }), "M3 3h18v18H3z");
  assert.equal(toPathD("rect", { x: "2", y: "2", width: "20", height: "20", rx: "5" }), "M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5z");
  assert.equal(toPathD("circle", { cx: "12", cy: "12", r: "10" }), "M2 12a10 10 0 1 0 20 0a10 10 0 1 0-20 0");
  assert.equal(toPathD("ellipse", { cx: "12", cy: "5", rx: "9", ry: "3" }), "M3 5a9 3 0 1 0 18 0a9 3 0 1 0-18 0");
  assert.equal(toPathD("line", { x1: "4", y1: "12", x2: "20", y2: "12" }), "M4 12L20 12");
  assert.equal(toPathD("polyline", { points: "4 12 8 16 20 4" }), "M4 12L8 16L20 4");
  assert.equal(toPathD("polygon", { points: "12,2 22,22 2,22" }), "M12 2L22 22L2 22z");
  assert.equal(toPathD("path", { d: "M1 1" }), "M1 1");
  assert.throws(() => toPathD("text", {}), /<text> is not a shape an icon is made of/);
});

test("parseIcon reads a Lucide file into stroke paths and a Simple Icons file into one fill path", () => {
  const lucide = `<!-- @license lucide-static v1.47.0 - ISC -->\n<svg class="lucide lucide-database" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">\n  <ellipse cx="12" cy="5" rx="9" ry="3" />\n  <path d="M3 5V19A9 3 0 0 0 21 19V5" />\n</svg>\n`;
  assert.deepEqual(parseIcon(lucide, "lucide"), { kind: "stroke", d: ["M3 5a9 3 0 1 0 18 0a9 3 0 1 0-18 0", "M3 5V19A9 3 0 0 0 21 19V5"] });
  // a <line>'s attributes carry digits in their names (x1, y2): they must be read, not skipped into NaN (0.4.3)
  const server = `<svg viewBox="0 0 24 24"><rect width="20" height="8" x="2" y="2" rx="2" ry="2" /><line x1="6" x2="6.01" y1="6" y2="6" /></svg>`;
  assert.deepEqual(parseIcon(server, "lucide"), { kind: "stroke", d: ["M4 2h16a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z", "M6 6L6.01 6"] });
  const si = `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>NVIDIA</title><path d="M8.948 8.798v-1.43z"/></svg>`;
  assert.deepEqual(parseIcon(si, "si"), { kind: "fill", d: "M8.948 8.798v-1.43z", title: "NVIDIA" });
});

test("readIconSource reads from the packages a site installs, and names the install when one is missing", () => {
  const site = fs.mkdtempSync(path.join(os.tmpdir(), "icons-"));
  const put = (file, text) => { fs.mkdirSync(path.dirname(path.join(site, file)), { recursive: true }); fs.writeFileSync(path.join(site, file), text); };
  put("node_modules/lucide-static/package.json", '{"name":"lucide-static","version":"1.47.0","license":"ISC"}');
  put("node_modules/lucide-static/LICENSE", "ISC License\n\nCopyright (c) 2026 Lucide Icons and Contributors\n\nPermission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\"…\n");
  put("node_modules/lucide-static/icons/house.svg", `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M15 21v-8"/><path d="M3 10a2 2 0 0 1 1-1z"/></svg>`);
  put("node_modules/simple-icons/package.json", '{"name":"simple-icons","version":"16.31.0","license":"CC0-1.0"}');
  put("node_modules/simple-icons/icons/nvidia.svg", `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>NVIDIA</title><path d="M8 8z"/></svg>`);
  assert.deepEqual(readIconSource("lucide:house", site), { id: "lucide:house", kind: "stroke", d: ["M15 21v-8", "M3 10a2 2 0 0 1 1-1z"] });
  assert.deepEqual(readIconSource("si:nvidia", site), { id: "si:nvidia", kind: "fill", d: "M8 8z", title: "NVIDIA" });
  assert.throws(() => readIconSource("lucide:nope", site), /lucide:nope: no such icon in lucide-static 1\.47\.0 \(the names are the file names under node_modules\/lucide-static\/icons\)/);
  assert.throws(() => readIconSource("si:nope", site), /si:nope: no such icon in simple-icons 16\.31\.0/);
  assert.throws(() => readIconSource("other:x", site), /other:x: an id is lucide:<name>, si:<slug> or file:<name>/);
  fs.rmSync(path.join(site, "node_modules/simple-icons"), { recursive: true });
  assert.throws(() => readIconSource("si:nvidia", site), /simple-icons is not installed: pnpm add -D simple-icons/);
  const map = renderIconMap([readIconSource("lucide:house", site)], { site });
  assert.match(map, /^\/\/ generated by agentic-cms icons from src\/config\/icons\.json; do not edit by hand — agentic-cms icons add\|remove <id>/);
  assert.match(map, /Lucide icons \(lucide-static 1\.47\.0\): ISC License[\s\S]*Copyright \(c\) 2026 Lucide Icons and Contributors[\s\S]*Permission to use/);
  assert.match(map, /import type \{ IconData \} from "agentic-cms\/components";/);
  assert.match(map, /export const ICONS = \{\n  "lucide:house": \{ kind: "stroke", d: \["M15 21v-8", "M3 10a2 2 0 0 1 1-1z"\] \},\n\} as const satisfies Record<string, IconData>;/);
  assert.doesNotMatch(map, /Simple Icons/, "the CC0 line appears only when a Simple Icon is in the map");
  fs.rmSync(site, { recursive: true, force: true });
});

test("file:<name> reads the site's own drawing: its paint decides the kind, its viewBox is kept off the 24 grid, and anything but flat shapes is refused", () => {
  const site = fs.mkdtempSync(path.join(os.tmpdir(), "icons-"));
  const put = (file, text) => { fs.mkdirSync(path.dirname(path.join(site, file)), { recursive: true }); fs.writeFileSync(path.join(site, file), text); };
  put("src/config/icons/house.svg", `<!-- rendered by agentic-cms lab from .parity/lab/house.svg -->\n<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="1.6"><rect x="3" y="3" width="18" height="18"/><path d="M3 3l18 18"/></svg>`);
  put("src/config/icons/mark.svg", `<svg viewBox="0 0 64 64"><title>The mark</title><circle cx="32" cy="32" r="20"/><path d="M0 0L64 64"/></svg>`);
  put("src/config/icons/grouped.svg", `<svg viewBox="0 0 24 24"><g transform="rotate(45)"><rect width="4" height="4"/></g></svg>`);
  put("src/config/icons/styled.svg", `<svg viewBox="0 0 24 24"><style>.a{fill:red}</style><rect class="a" width="4" height="4"/></svg>`);
  put("src/config/icons/empty.svg", `<svg viewBox="0 0 24 24"></svg>`);
  assert.deepEqual(readIconSource("file:house", site), { id: "file:house", kind: "stroke", d: ["M3 3h18v18H3z", "M3 3l18 18"] });
  assert.deepEqual(readIconSource("file:mark", site), { id: "file:mark", kind: "fill", d: "M12 32a20 20 0 1 0 40 0a20 20 0 1 0-40 0M0 0L64 64", viewBox: "0 0 64 64", title: "The mark" });
  assert.throws(() => readIconSource("file:grouped", site), /file:grouped: <g: an icon is flat shapes with one paint — no group, transform, use, defs, style, mask, clipPath or text; flatten it first/);
  assert.throws(() => readIconSource("file:styled", site), /file:styled: <style: an icon is flat shapes/);
  assert.throws(() => readIconSource("file:empty", site), /file:empty: no shapes in the icon/);
  assert.throws(() => readIconSource("file:nope", site), /file:nope: no src\/config\/icons\/nope\.svg \(draw it in the lab and render it there: agentic-cms lab render <scene> --out src\/config\/icons\/nope\.svg\)/);
  assert.throws(() => readIconSource("file:../secret", site), /file:\.\.\/secret: a file icon's name is lowercase letters, digits and hyphens/);
  assert.throws(() => readIconSource("file:Mark", site), /a file icon's name is lowercase/);
  assert.deepEqual(readIconSource("file:mark", site, { iconsDir: "src/config/icons" }).viewBox, "0 0 64 64");
  const map = renderIconMap([readIconSource("file:house", site), readIconSource("file:mark", site)], { site });
  assert.match(map, /^\/\/ generated by agentic-cms icons[^\n]*\n\/\/ The site's own icons: src\/config\/icons\/<name>\.svg, drawn in the lab \(agentic-cms lab\)\nimport type/);
  assert.match(map, /"file:house": \{ kind: "stroke", d: \["M3 3h18v18H3z", "M3 3l18 18"\] \},/);
  assert.match(map, /"file:mark": \{ kind: "fill", d: "M12 32a20 20 0 1 0 40 0a20 20 0 1 0-40 0M0 0L64 64", viewBox: "0 0 64 64", title: "The mark" \},/);
  fs.rmSync(site, { recursive: true, force: true });
});
