import assert from "node:assert/strict";
import { test } from "node:test";
import { renderFamily } from "./icons-family.mjs";

const spec = {
  gradients: {
    warm: { x2: 1, y2: 0, stops: [["0", "#F46D6B"], [".5", "#FBB17D"], ["1", "#F46D6B"]] },
    glass: { x2: 1, y2: 1, stops: [["0", "#fff", ".34"], ["1", "#fff", ".16"]] },
    grey: { x2: 1, y2: 1, stops: [[".45", "#66687D"], ["1", "#9F9494", ".9"]] },
    edge: { x2: 0, y2: 1, stops: [["0", "#fff"], ["1", "#fff", "0"]] },
  },
  paint: "warm",
  ring: { size: 40, radius: 19.5, stroke: "white", opacity: 0.5, scale: 0.34375, offset: 9 },
  marks: {
    perimeter: { out: "public/images/benefit-perimeter.svg", size: 33, parts: [["glass", 4, 4, 56, 56, 9], ["tile", 19, 19, 26, 26, 5]] },
    email: { out: "public/images/icon-email.svg", size: 34, parts: [["tile", 6, 15, 52, 36, 6], ["poly", "6,19 58,19 32,41", "grey"], ["glass", 38, 36, 22, 16, 4]] },
    medal: { out: "public/images/medal.svg", size: 24, parts: [["tile", 20, 34, 11, 26, 2.5, { grad: "warm", rot: 14, cx: 25.5, cy: 47 }], ["disc", 32, 23, 17], ["glassDisc", 32, 23, 8], ["stroke", "M22 32 L29 39 L42 25", 4.4], ["ring", 46, 32, 12, 6], ["glassRing", 18, 32, 12, 6], ["grey", 6, 13, 52, 6, 3]] },
    independence: { out: "public/images/own-independence.svg", size: 40, ring: true, parts: [["glassRing", 18, 32, 12, 6], ["ring", 46, 32, 12, 6]] },
  },
};

test("a mark is the defs, then its parts, on the grid, sized as declared, with the generated header", () => {
  const files = renderFamily(spec, { from: "content/icons.yaml" });
  assert.deepEqual([...files.keys()], ["public/images/benefit-perimeter.svg", "public/images/icon-email.svg", "public/images/medal.svg", "public/images/own-independence.svg"]);
  const svg = files.get("public/images/benefit-perimeter.svg");
  assert.match(svg, /^<!-- generated by agentic-cms icons family from content\/icons\.yaml; do not hand-edit -->\n/);
  assert.match(svg, /<svg width="33" height="33" viewBox="0 0 64 64" fill="none" xmlns="http:\/\/www\.w3\.org\/2000\/svg">/);
  assert.match(svg, /<linearGradient id="warm" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#F46D6B"\/><stop offset="\.5" stop-color="#FBB17D"\/><stop offset="1" stop-color="#F46D6B"\/><\/linearGradient>/);
  assert.match(svg, /<linearGradient id="glass"[^>]*><stop offset="0" stop-color="#fff" stop-opacity="\.34"\/>/);
  assert.match(svg, /<rect x="4" y="4" width="56" height="56" rx="9" fill="url\(#glass\)" stroke="url\(#edge\)" stroke-width="\.5"\/>\n<rect x="19" y="19" width="26" height="26" rx="5" fill="url\(#warm\)"\/>/);
});

test("every primitive renders as the reference language does", () => {
  const svg = renderFamily(spec, { from: "x" }).get("public/images/medal.svg");
  assert.match(svg, /<rect x="20" y="34" width="11" height="26" rx="2\.5" fill="url\(#warm\)" transform="rotate\(14 25\.5 47\)"\/>/);
  assert.match(svg, /<circle cx="32" cy="23" r="17" fill="url\(#warm\)"\/>/);
  assert.match(svg, /<circle cx="32" cy="23" r="8" fill="url\(#glass\)" stroke="url\(#edge\)" stroke-width="\.5"\/>/);
  assert.match(svg, /<path d="M22 32 L29 39 L42 25" fill="none" stroke="#fff" stroke-width="4\.4" stroke-linecap="round" stroke-linejoin="round"\/>/);
  assert.match(svg, /<circle cx="46" cy="32" r="12" fill="none" stroke="url\(#warm\)" stroke-width="6"\/>/);
  assert.match(svg, /<circle cx="18" cy="32" r="12" fill="none" stroke="#fff" stroke-opacity="\.3" stroke-width="6"\/>/);
  assert.match(svg, /<rect x="6" y="13" width="52" height="6" rx="3" fill="url\(#grey\)" fill-opacity="\.6" stroke="url\(#edge\)" stroke-width="\.5"\/>/);
  const email = renderFamily(spec, { from: "x" }).get("public/images/icon-email.svg");
  assert.match(email, /<polygon points="6,19 58,19 32,41" fill="url\(#grey\)" fill-opacity="\.6" stroke-linejoin="round" stroke="url\(#edge\)" stroke-width="\.5"\/>/);
});

test("a ringed mark is the ring's canvas with the parts scaled inside it", () => {
  const svg = renderFamily(spec, { from: "x" }).get("public/images/own-independence.svg");
  assert.match(svg, /<svg width="40" height="40" viewBox="0 0 40 40"/);
  assert.match(svg, /<circle opacity="0\.5" cx="20" cy="20" r="19\.5" stroke="white"\/>\n<g transform="translate\(9 9\) scale\(0\.34375\)">/);
});

test("rendering is deterministic, and a spec naming an unknown primitive or gradient is refused with the mark named", () => {
  assert.deepEqual([...renderFamily(spec, { from: "x" }).entries()], [...renderFamily(spec, { from: "x" }).entries()]);
  assert.throws(() => renderFamily({ ...spec, marks: { bad: { out: "x.svg", size: 10, parts: [["blob", 1]] } } }, { from: "x" }), /marks\.bad: no primitive "blob" \(tile, glass, grey, disc, glassDisc, ring, glassRing, stroke, poly\)/);
  assert.throws(() => renderFamily({ ...spec, marks: { bad: { out: "x.svg", size: 10, parts: [["tile", 1, 1, 1, 1, 1, { grad: "neon" }]] } } }, { from: "x" }), /marks\.bad: no gradient "neon" in gradients/);
  assert.throws(() => renderFamily({ ...spec, marks: { bad: { size: 10, parts: [] } } }, { from: "x" }), /marks\.bad: needs out \(the file\), size \(px\) and parts/);
});
