// The command line's contract, one spec per command (scripts/lib/args.mjs
// says the shape). bin/agentic-cms.mjs dispatches and prints `--help` from
// it, every script parses its arguments through it, and
// tools/commands-doc.mjs writes docs/commands.md from it — one source, so the
// parser, the help and the docs cannot disagree. Exit codes: 0 clean, 1
// findings or differences, 2 usage or environment.
const root = { type: "string", value: "<dir>", help: "another site tree (its content/ and public/) instead of the current directory" };
const report = (file) => ({ type: "boolean", help: `also write the findings to ${file}` });
const strict = { type: "boolean", help: "every WARN counts as a FAIL" };
const dryRun = { type: "boolean", help: "print what would change; write nothing" };

export const SPECS = {
  lint: {
    command: "lint", script: "content-lint", group: "content", site: true, summary: "the content rules: every collection read as the build reads it, then the voice, SEO, body, image and date rules",
    usage: "agentic-cms lint [--root <dir>] [--strict] [--report] [--json]",
    flags: { root, strict, report: report(".parity/content-lint-report.txt"), json: { type: "boolean", help: "print the findings as one JSON document (the progress goes to stderr)" } },
    examples: ["agentic-cms lint", "agentic-cms lint --strict --report        # every WARN counts; the findings also in .parity/content-lint-report.txt", "agentic-cms lint --json | jq '.findings[] | select(.level == \"FAIL\")'"],
    exit: { 0: "no FAIL", 1: "a FAIL (a WARN is read, not failed, unless --strict)", 2: "not a site (no src/kit.ts here)" },
    json: "{ root, collections: [{ name, entries, source }], findings: [{ level, file, rule, path, problem }], summary: { fails, warns, strict } }",
  },
  check: {
    command: "check", script: "content-check", group: "content", site: true, summary: "the schemas alone: every collection read, one row each, in a fraction of a second",
    usage: "agentic-cms check [--root <dir>]",
    flags: { root },
    examples: ["agentic-cms check", "agentic-cms check --root ../other-site"],
    exit: { 0: "every collection reads", 1: "a ContentError (its lines printed, one per issue)" },
  },
  status: {
    command: "status", script: "content-status", group: "content", site: true, summary: "what is live, in draft and planned, read from the files: posts, pages, FAQ sets, reviews, use cases, the calendar, the backlog, recent changes",
    usage: "agentic-cms status [--since 30.days]",
    flags: { since: { type: "string", default: "30.days", value: "<git window>", help: "how far back the recent-changes list looks" } },
    examples: ["agentic-cms status", "agentic-cms status --since 7.days"],
    exit: { 0: "printed" },
  },
  docs: {
    command: "docs", script: "content-docs", group: "content", site: true, summary: "the field tables of every collection, from the schemas, into content/README.md between its markers",
    usage: "agentic-cms docs [--check]",
    flags: { check: { type: "boolean", help: "exit 1 when the tables are out of date instead of writing them (pnpm build runs this)" } },
    examples: ["agentic-cms docs                          # writes the field tables into content/README.md", "agentic-cms docs --check                  # exit 1 when they are stale (pnpm build runs this)"],
    exit: { 0: "written, or up to date", 1: "out of date (--check)", 2: "content/README.md has no markers" },
  },
  seo: {
    command: "seo", script: "check-seo", group: "build gates", site: true, summary: "the audit of every prerendered page after next build: title, description, canonical, Open Graph, headings, images, JSON-LD, robots, sitemap, internal links",
    usage: "agentic-cms seo [--strict] [--report] [--json]",
    flags: { strict, report: report(".parity/seo-report.txt"), json: { type: "boolean", help: "print the findings as one JSON document" } },
    examples: ["agentic-cms seo                           # after next build", "agentic-cms seo --strict --json"],
    exit: { 0: "no FAIL", 1: "a FAIL", 2: "no build under .next/server/app" },
    json: "{ pages, findings: [{ level, route, rule, problem }], summary: { fails, warns, strict } }",
  },
  placeholder: {
    command: "placeholder", script: "placeholder", group: "images", summary: "one wireframe placeholder image: a grey field, a hairline border, a corner-to-corner cross; the format follows the extension (.svg, .webp, .jpg, .png)",
    usage: "agentic-cms placeholder <out> <width> <height>",
    positionals: [{ name: "out", required: true, help: "the file to write" }, { name: "width", required: true, help: "pixels" }, { name: "height", required: true, help: "pixels" }],
    examples: ["agentic-cms placeholder public/images/home/hero.webp 1600 900", "agentic-cms placeholder public/images/sections-about-og.jpg 1200 630"],
    exit: { 0: "written", 2: "usage, or an extension that is not .svg/.webp/.jpg/.jpeg/.png" },
  },
  "optimize-webp": {
    command: "optimize-webp", script: "optimize-webp", group: "images", summary: "re-encodes WebP files as lossy WebP in place when that saves enough (design exports are usually lossless)",
    usage: "agentic-cms optimize-webp [--quality 80] [--max-width <n>] [--min-saving 30] [--dry-run] <files-or-dirs...>",
    positionals: [{ name: "files", required: true, variadic: true, help: "files, or directories walked for .webp" }],
    flags: { quality: { type: "number", default: 80, help: "WebP quality" }, "max-width": { type: "number", default: 0, help: "also downscale pictures wider than this (0: never)" }, "min-saving": { type: "number", default: 30, help: "rewrite only when the saving is at least this percent" }, "dry-run": dryRun },
    examples: ["agentic-cms optimize-webp public/images/blog/my-post", "agentic-cms optimize-webp --dry-run --max-width 1600 public/images"],
    exit: { 0: "done (a file that would not save enough is kept and says so)", 2: "a file or folder that does not exist, or usage" },
  },
  "optimize-svg-rasters": {
    command: "optimize-svg-rasters", script: "optimize-svg-rasters", group: "images", summary: "re-encodes the PNGs that design-tool SVG exports embed as base64 into WebP, in place; the drawing is untouched",
    usage: "agentic-cms optimize-svg-rasters [--lossy] [--dry-run] [files...]",
    positionals: [{ name: "files", variadic: true, help: "SVG files; without any, every SVG under public/images" }],
    flags: { lossy: { type: "boolean", help: "allow quality-80 WebP where it is smaller (for bitmaps used as alpha masks only)" }, "dry-run": dryRun },
    examples: ["agentic-cms optimize-svg-rasters              # every SVG under public/images", "agentic-cms optimize-svg-rasters --lossy public/images/home/diagram.svg"],
    exit: { 0: "done", 2: "a file that does not exist, or usage" },
  },
  parity: {
    command: "parity", script: "parity", group: "proof", summary: "builds, then stores every prerendered page (scripts and hashed links stripped), its JSON-LD and the non-HTML routes under .parity/<label>/ for a diff -r",
    usage: "agentic-cms parity <label>",
    positionals: [{ name: "label", required: true, help: "the capture's name under .parity/" }],
    examples: ["agentic-cms parity before && … refactor … && agentic-cms parity after && diff -r .parity/before .parity/after"],
    exit: { 0: "stored", 2: "the build failed (see .parity/<label>.build.log), or usage" },
  },
  "visual-parity": {
    command: "visual-parity", script: "visual-parity", group: "proof", summary: "the screenshot harness: every page of the build at several widths, frozen or in motion, and a pixel diff of two captures",
    usage: "agentic-cms visual-parity <capture | compare> …",
    subcommands: {
      capture: {
        command: "visual-parity capture", summary: "screenshots of the build (or of a served site) into .parity/visual/<label>/; the site's own build is copied first, so the tree is free once the snapshot line is printed",
        usage: "agentic-cms visual-parity capture <label> [--motion | --states] [--scheme light|dark] [--url <base>] [--widths w,w] [--pages /a,/b] [--jobs <n>] [--fresh]",
        positionals: [{ name: "label", required: true, help: "the capture's name under .parity/visual/" }],
        flags: {
          motion: { type: "boolean", help: "play the animations: viewport frames 150, 500 and 2000 ms after each scroll step, plus an inventory of every animation" },
          states: { type: "boolean", help: "hover, focus, checked and open states, located by role and text" },
          scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "prefers-color-scheme for the capture" },
          url: { type: "string", value: "<base>", help: "capture a served site instead of serving .next (print its git log -1 first)" },
          build: { type: "boolean", help: "run the site's `pnpm build` first (log: .parity/<label>.build.log)" },
          ref: { type: "string", value: "<git ref>", help: "capture a baseline: that commit checked out in a sibling directory (../<site>-ref-<sha>), its demo routes removed, installed, built (reused for the same sha once a build finished), served and captured" },
          widths: { type: "string", value: "w,w", help: "viewport widths; default 1920,1440,1280,1100,992,800,767,390 (1440,390 with --motion)" },
          pages: { type: "string", value: "/a,/b", help: "only these routes (a partial capture; pass the same to compare); a demo route (/<name>-demo) is captured only when named here" },
          settle: { type: "number", default: 2000, help: "with --motion: the ms after a scroll step at which the settled frame is taken; an element's data-settle=\"<ms>\" raises it while that element is in view" },
          jobs: { type: "number", value: "<n>", help: "browsers at work at once, each on its own page-widths (or states): default the cores less one, at most 4, for a static or --states capture, and 2 for --motion, whose frames are timed" },
          fresh: { type: "boolean", help: "take every shot again: reuse none from .parity/shots, where a page-width whose build files are all unchanged is otherwise copied (the cache is refreshed all the same)" },
          json: { type: "boolean", help: "print the capture's summary as JSON (also written last as capture.json — its presence means the capture finished)" },
        },
        examples: ["agentic-cms visual-parity capture before --ref develop", "agentic-cms visual-parity capture after --scheme dark --pages /,/blog", "agentic-cms visual-parity capture after --motion --json"],
        exit: { 0: "captured", 1: "a page failed twice (no shot is taken of a stalled page), or the build failed", 2: "usage, no build, or no browser (playwright-core and a Chromium)" },
        json: "{ label, dir, pages, widths, files, seconds, jobs, reused: { shots, of } | null, timings: { taken, seconds, mean, slowest: [{ name, seconds }] }, meta: { scheme, motion, states, settle, ref, sha, tree: { head, dirty } | null } }",
      },
      compare: {
        command: "visual-parity compare", summary: "diffs two captures pixel by pixel; diff images under .parity/visual/<before>-vs-<after>/",
        usage: "agentic-cms visual-parity compare <before> <after> [--threshold 0.02] [--threshold-mid 20] [--pages /a,/b]",
        positionals: [{ name: "before", required: true, help: "the baseline's label" }, { name: "after", required: true, help: "the label to judge" }],
        flags: {
          threshold: { type: "number", default: 0.02, help: "percent of pixels a static or settled frame may differ by" },
          "threshold-mid": { type: "number", default: 20, help: "the same for the mid-flight motion frames (150 and 500 ms)" },
          pages: { type: "string", value: "/a,/b", help: "judge only these routes' files, on both sides, at the widths the after capture took (a partial capture)" },
          json: { type: "boolean", help: "print the report as JSON (also written as report.json in the diff directory)" },
        },
        examples: ["agentic-cms visual-parity compare before after --json", "agentic-cms visual-parity compare before after --pages /,/blog"],
        exit: { 0: "identical within the thresholds", 1: "a difference, a size change or a missing file", 2: "usage, a missing capture, or captures of two schemes" },
        json: "{ before, after, scheme, threshold, thresholdMid, pages, baseline, geometry: { before, after }, summary: { ok, changed, size, missing, exit }, files: [{ name, kind, status, line, … changedPct, bands | verdict, head, tail, delta, band, crops | onlyBefore, onlyAfter | in, cause: { section, id, moved, top, height, delta, fractional } | null }] }",
      },
    },
  },
  shot: {
    command: "shot", script: "shot", group: "look & measure", summary: "one screenshot of a page or of an element on it, prepared like the harness prepares a page, with its box as JSON",
    usage: "agentic-cms shot <route|url> [--url <base>] [--width 1440] [--height 900] [--scale 1] [--select <css> | --heading <regex>] [--transparent] [--trim] [--resize <w>] [--out <file>] [--json]",
    positionals: [{ name: "target", required: true, help: "a route of the build (/about) or a URL" }],
    flags: {
      url: { type: "string", value: "<base>", help: "a served site (a dev server) instead of the build under .next" },
    width: { type: "number", default: 1440, help: "viewport width in px" },
    height: { type: "number", default: 900, help: "viewport height in px" },
    scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "prefers-color-scheme" },
    motion: { type: "boolean", help: "play the animations (reveals at their start state, sequences running) instead of freezing them at the end state" },
    wait: { type: "number", default: 0, help: "extra milliseconds to wait before measuring or photographing" },
    scroll: { type: "string", value: "<y|into-view>", help: "scroll the page to y px, or the target into view (the default with a target under --motion)" },
    select: { type: "string", value: "<css>", help: "the element: a CSS selector (the first match, or --index); with --heading, searched inside that section" },
    heading: { type: "string", value: "<regex>", help: "the element: the section (article, [data-section]) holding the heading that matches — or, with --select, the section the selector is searched in" },
    index: { type: "number", default: 0, help: "which match of --select or --heading, from 0" },
      scale: { type: "number", default: 1, help: "device scale factor (2 for a crisp crop)" },
      pad: { type: "number", default: 24, help: "margin around the element's box, in px" },
      transparent: { type: "boolean", help: "the element alone on a transparent ground: everything else hidden, the ancestors' backgrounds cleared" },
      trim: { type: "boolean", help: "trim the transparent or same-colour edges (sharp)" },
      resize: { type: "number", default: 0, help: "scale the result to this width in px (0: as photographed)" },
      out: { type: "string", value: "<file>", help: ".png or .webp; default .parity/shots/<route>@<width>[--<target>].png" },
      json: { type: "boolean", help: "print one JSON document on stdout (progress goes to stderr)" },
    },
    examples: ["agentic-cms shot / --width 390 --scheme dark", "agentic-cms shot / --heading \"fits the stack\" --select \".card\" --scale 2 --json", "agentic-cms shot /about --url http://localhost:8000 --select \"picture\" --transparent --trim --out .parity/shots/loop.png"],
    exit: { 0: "written", 1: "the target was not found on the page", 2: "usage, no build, or no browser" },
    json: "{ url, route, width, height, scale, scheme, motion, scrollY, target: { by, value, index, tag, id, box, pageBox } | null, out, image: { width, height, transparent, trimmed, resized }, console }",
  },
  probe: {
    command: "probe", script: "probe", group: "look & measure", summary: "the numbers behind a screenshot claim: an element's box, computed styles and stacking contexts, the reveals still pending, the console — JSON only",
    usage: "agentic-cms probe <route|url> --select <css> | --heading <regex> [--all] [--props <list>] [--timeline <ms> [--every 100]] [--url <base>] [--width 1440] [--motion]",
    positionals: [{ name: "target", required: true, help: "a route of the build (/about) or a URL" }],
    flags: {
      url: { type: "string", value: "<base>", help: "a served site (a dev server) instead of the build under .next" },
    width: { type: "number", default: 1440, help: "viewport width in px" },
    height: { type: "number", default: 900, help: "viewport height in px" },
    scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "prefers-color-scheme" },
    motion: { type: "boolean", help: "play the animations (reveals at their start state, sequences running) instead of freezing them at the end state" },
    wait: { type: "number", default: 0, help: "extra milliseconds to wait before measuring or photographing" },
    scroll: { type: "string", value: "<y|into-view>", help: "scroll the page to y px, or the target into view (the default with a target under --motion)" },
    select: { type: "string", value: "<css>", help: "the element: a CSS selector (the first match, or --index); with --heading, searched inside that section" },
    heading: { type: "string", value: "<regex>", help: "the element: the section (article, [data-section]) holding the heading that matches — or, with --select, the section the selector is searched in" },
    index: { type: "number", default: 0, help: "which match of --select or --heading, from 0" },
      all: { type: "boolean", help: "every match of --select or --heading, not just one" },
      props: { type: "string", value: "<a,b>", help: "computed properties to add to the default set (opacity, transform, position, z-index, display, visibility, overflow, color, background-color, font-size, line-height, width, height, margin, padding)" },
      timeline: { type: "number", default: 0, help: "with --motion: scroll the element into view and sample opacity, transform and box top for this many ms" },
      every: { type: "number", default: 100, help: "the timeline's sampling interval in ms" },
    },
    examples: ["agentic-cms probe / --select \".card\" --all", "agentic-cms probe / --heading \"pricing\" --motion --timeline 2000 --every 100"],
    exit: { 0: "printed", 1: "no element matched", 2: "usage, no build, or no browser" },
    json: "{ url, route, width, height, scheme, motion, scrollY, scrollHeight, elements: [{ selector, index, tag, id, classes, box, pageBox, computed, stacking: [{ tag, id, classes, reason }], timeline? }], reveals: { total, pending: [{ tag, id, classes, pageTop, opacity }] }, console }",
  },
  sheet: {
    command: "sheet", script: "sheet", group: "look & measure", summary: "a candidate sheet from a spec — rows lettered, cells at the real size on the real background — rendered to one picture for a pick by row",
    usage: "agentic-cms sheet <spec.yaml|json> [--url <base>] [--out <png>] [--scale 2] [--scheme light|dark] [--json]",
    positionals: [{ name: "spec", required: true, help: "the sheet: { name, background, color, rows: [{ label, note, size, cells: [{ label, file | svg | html | img, size?, ground?: { background, color } }] } | { label, note, files: <dir | [files]>, sizes, grounds }] }" }],
    flags: {
      url: { type: "string", value: "<base>", help: "serve img: cells and the site's stylesheets from a served site instead of the build" },
      out: { type: "string", value: "<png>", help: "default .parity/sheets/<name>.png" },
      scale: { type: "number", default: 2, help: "device scale factor" },
      scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "prefers-color-scheme (tokens follow it)" },
      width: { type: "number", default: 1200, help: "the sheet's width in px" },
      json: { type: "boolean", help: "print one JSON document on stdout" },
    },
    examples: ["agentic-cms sheet .parity/sector-icons.yaml", "agentic-cms sheet .parity/marks.yaml --scheme dark --url http://localhost:8000"],
    exit: { 0: "written", 2: "usage, a spec error (the field is named), a missing file, or no browser" },
    json: "{ file, name, rows: [{ id, label, cells }], width, height }",
  },
  init: {
    command: "init", script: "init", group: "site", summary: "a site from the package: the wireframe example, the agent files (rules and design skills), the config and a manifest; or a refresh of an existing site's agent files",
    usage: "agentic-cms init [dir] [--force] | agentic-cms init [dir] --agent-files [--check] [--force]",
    positionals: [{ name: "dir", help: "where the site goes (default: the current directory)" }],
    flags: {
      "agent-files": { type: "boolean", help: "only the rules (.claude/rules/) and the design skills (.claude/skills/, .agents/skills/); a file the site edited is kept" },
      check: { type: "boolean", help: "with --agent-files: report each file — ok, modified (the site edited it), stale (the kit has a newer one), missing — and exit 1 on any drift; write nothing" },
      force: { type: "boolean", help: "overwrite files that exist (package.json is always merged, never overwritten)" },
      json: { type: "boolean", help: "print the result as JSON" },
    },
    examples: ["agentic-cms init .", "agentic-cms init . --agent-files          # after a kit upgrade: the new rules and skills", "agentic-cms init . --agent-files --check  # what drifted, for CI"],
    exit: { 0: "written, or every agent file as the kit ships it", 1: "--check found drift", 2: "usage" },
    json: "{ target, version, created, updated, kept } | { version, files: [{ file, status }] }",
  },
  "guard-email": {
    command: "guard-email", script: "guard-email", group: "build gates", site: true, summary: "fails when a served file of the build (a page, an RSC payload, the feed, a bundle) carries the site's e-mail address as text",
    usage: "agentic-cms guard-email [--domain <host>]… [--json]",
    flags: {
      domain: { type: "string", multiple: true, value: "<host>", help: "a domain whose addresses must not appear; default: the host of site.url from src/kit.ts" },
      json: { type: "boolean", help: "print { domains, scanned, hits: [{ file, addresses }] }" },
    },
    examples: ["agentic-cms guard-email", "agentic-cms guard-email --domain acme.example --json"],
    exit: { 0: "no address as text", 1: "an address in a served file (each named)", 2: "usage, or no build under .next" },
    json: "{ domains, scanned, hits: [{ file, addresses }] }",
  },
  assemble: {
    command: "assemble", script: "assemble", group: "build gates", summary: "packages a standalone build for a Node host: public/ and .next/static copied into .next/standalone — into its folders, never as them — then every file of both checked there",
    usage: "agentic-cms assemble [--check] [--json]",
    flags: {
      check: { type: "boolean", help: "copy nothing: only check the package against public/ and .next/static (in CI, or after a copy made by hand)" },
      json: { type: "boolean", help: "print the report as one JSON document" },
    },
    examples: ["agentic-cms assemble                      # after next build: the last step of a standalone site's build", "agentic-cms assemble --check --json"],
    exit: { 0: "the package holds every file of public/ and .next/static", 1: "a file missing or different, or a copy nested inside the folder it should fill (each named)", 2: "usage, or no standalone build (output: \"standalone\", then next build)" },
    json: "{ package, copied, removed, parts: [{ from, files, bytes }], missing, differ, nested, extra }",
  },
  icons: {
    command: "icons", script: "icons", group: "icons", summary: "the site's icons: a map of Lucide and Simple Icons paths kept from a manifest, a family of marks rendered from primitives, an audit of every icon on the built pages, and a design round for a set of the site's own",
    usage: "agentic-cms icons <add | remove | family | audit | round> …",
    subcommands: {
      add: {
        command: "icons add", summary: "adds ids (lucide:<name>, si:<slug>, file:<name>) to src/config/icons.json and regenerates src/config/icons.ts from the sets the site installs and its own drawings under src/config/icons/; an id already there is a no-op, so this also regenerates",
        usage: "agentic-cms icons add <id>… [--manifest src/config/icons.json] [--json]",
        positionals: [{ name: "ids", required: true, variadic: true, help: "lucide:<name> (the file names under node_modules/lucide-static/icons), si:<slug> (simple-icons), or file:<name> (the site's own src/config/icons/<name>.svg: flat shapes, one paint, its viewBox kept — drawn in the lab)" }],
        flags: { manifest: { type: "string", default: "src/config/icons.json", value: "<file>", help: "the list of ids; the map is written beside it as .ts" }, json: { type: "boolean", help: "print { manifest, map, ids, added }" } },
        examples: ["agentic-cms icons add lucide:house lucide:database si:nvidia", "agentic-cms icons add file:pipeline           # src/config/icons/pipeline.svg, drawn in the lab"],
        exit: { 0: "written", 2: "an unknown id, a set that is not installed (pnpm add -D lucide-static simple-icons), a file icon that is missing or not flat shapes, or usage" },
        json: "{ manifest, map, ids, added }",
      },
      remove: {
        command: "icons remove", summary: "removes ids from the manifest and regenerates the map",
        usage: "agentic-cms icons remove <id>… [--manifest src/config/icons.json] [--json]",
        positionals: [{ name: "ids", required: true, variadic: true, help: "the ids to drop" }],
        flags: { manifest: { type: "string", default: "src/config/icons.json", value: "<file>", help: "the list of ids" }, json: { type: "boolean", help: "print { manifest, map, ids, removed }" } },
        examples: ["agentic-cms icons remove si:nvidia"],
        exit: { 0: "written", 2: "a set that is not installed, or usage" },
        json: "{ manifest, map, ids, removed }",
      },
      family: {
        command: "icons family", summary: "renders a family of marks from a spec of primitives (tile, glass, grey, disc, glassDisc, ring, glassRing, stroke, poly on one grid, named gradients) to their SVG files",
        usage: "agentic-cms icons family <spec.yaml|json> [--check] [--json]",
        positionals: [{ name: "spec", required: true, help: "{ grid, gradients, paint, ring, marks: { <name>: { out, size, ring?, parts: [[primitive, …args, { named }?]] } } }" }],
        flags: { check: { type: "boolean", help: "write nothing; exit 1 listing the files that differ from what the spec renders" }, json: { type: "boolean", help: "print { marks, written | drift }" } },
        examples: ["agentic-cms icons family src/config/icon-family.yaml", "agentic-cms icons family src/config/icon-family.yaml --check"],
        exit: { 0: "written, or every file as the spec renders it", 1: "--check found drift", 2: "a spec error (the mark is named), or usage" },
        json: "{ marks, written } | { marks, drift }",
      },
      audit: {
        command: "icons audit", summary: "every icon on the built pages (an <img> up to --max px, an inline <svg>) with its size, colour, section, heading and the copy beside it — as JSON and as a sheet, one row per page",
        usage: "agentic-cms icons audit [--url <base>] [--pages /a,/b] [--max 96] [--out .parity/icons/audit.png] [--json]",
        flags: {
          url: { type: "string", value: "<base>", help: "a served site instead of the build under .next" },
          pages: { type: "string", value: "/a,/b", help: "only these routes (default: every page of the build but the 404)" },
          max: { type: "number", default: 96, help: "the largest rendered size counted as an icon, in px" },
          width: { type: "number", default: 1440, help: "viewport width the pages are measured at" },
          scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "prefers-color-scheme" },
          background: { type: "string", value: "<colour>", help: "the sheet's background (default the page's)" },
          color: { type: "string", value: "<colour>", help: "the sheet's ink" },
          out: { type: "string", value: "<png>", help: "the sheet; the JSON goes beside it (default .parity/icons/audit.png)" },
          json: { type: "boolean", help: "print the report" },
        },
        examples: ["agentic-cms icons audit                    # after next build; .parity/icons/audit.png and .json", "agentic-cms icons audit --pages /,/about --json"],
        exit: { 0: "written", 2: "no build, or no browser" },
        json: "{ pages, count, icons: [{ page, kind, src, width, height, renderedWidth, renderedHeight, color, alt, section, heading, copy, selector }], files: { src: { uses, pages } }, sheet }",
      },
      round: {
        command: "icons round", summary: "a design round for a set of icons, kept in the lab across sessions: scenes per role and letter to draw, a sheet of every candidate at its sizes on its grounds, the picks published where a page takes them, the round retired",
        usage: "agentic-cms icons round <new | publish | retire> …",
        subcommands: {
          new: {
            command: "icons round new", summary: "writes .parity/lab/rounds/<round>/: a scene per role and letter from the lab's icon or mark template to draw into a candidate, the round's record (round.yaml) and a sheet spec (sheet.yaml: a row per role, a cell per letter × size × ground on paper, white and black) for `agentic-cms sheet`; `lab serve` shows the scenes too, and `lab clean` leaves the round",
            usage: "agentic-cms icons round new <round> --roles <role,role> [--candidates 3] [--kind icon|mark] [--sizes 24,36,96] [--json]",
            positionals: [{ name: "round", required: true, help: "the round's name: lowercase letters, digits and hyphens" }],
            flags: {
              roles: { type: "string", value: "<role,role>", help: "the icons the round draws, one per role; a role becomes the published file's name" },
              candidates: { type: "number", default: 3, help: "letters per role, A onward (1 to 8)" },
              kind: { type: "string", default: "icon", choices: ["icon", "mark"], help: "icon: the Icon component's 24 grid in currentColor, published as inline Icon data; mark: the 64 grid, published as a file under public/" },
              sizes: { type: "string", default: "24,36,96", value: "px,px", help: "the sizes the sheet shows each candidate at: the sizes it ships at" },
              json: { type: "boolean", help: "print { round, dir, kind, scenes, sheet }" },
            },
            examples: ["agentic-cms icons round new modules --roles retrieval,graph,query", "agentic-cms icons round new plans --roles private,cloud --kind mark --sizes 48,96 --candidates 4"],
            exit: { 0: "written", 2: "a bad name, role, count, kind or size; a round that exists; or usage" },
            json: "{ round, dir, kind, scenes, sheet }",
          },
          publish: {
            command: "icons round publish", summary: "renders each pick where a page takes it — an icon as src/config/icons/<role>.svg and the icon map regenerated (icons add file:<role>), a mark as <to>/<role>.svg with its source beside it (<role>.source.svg) — and records the picks and the files in the round",
            usage: "agentic-cms icons round publish <round> --pick <role=letter,…> [--to public/images/icons] [--scheme light|dark] [--json]",
            positionals: [{ name: "round", required: true, help: "the round" }],
            flags: {
              pick: { type: "string", value: "<role=letter,…>", help: "the owner's pick per role: retrieval=B,graph=A" },
              to: { type: "string", default: "public/images/icons", value: "<dir>", help: "where a mark's file and its source go" },
              scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "the scheme a mark's file resolves the tokens for" },
              json: { type: "boolean", help: "print { round, published: [{ role, letter, files }] }" },
            },
            examples: ["agentic-cms icons round publish modules --pick retrieval=B,graph=A,query=C"],
            exit: { 0: "published", 2: "no such round, a role or letter it does not have, an icon that is not flat shapes, or usage" },
            json: "{ round, published: [{ role, letter, files }] }",
          },
          retire: {
            command: "icons round retire", summary: "removes the round's folder — its scenes, record and sheet — never what it published; a round with nothing published is kept unless --force",
            usage: "agentic-cms icons round retire <round> [--dry-run] [--force] [--json]",
            positionals: [{ name: "round", required: true, help: "the round" }],
            flags: {
              "dry-run": dryRun,
              force: { type: "boolean", help: "retire a round with nothing published" },
              json: { type: "boolean", help: "print { removed, kept, dryRun? }" },
            },
            examples: ["agentic-cms icons round retire modules", "agentic-cms icons round retire modules --dry-run"],
            exit: { 0: "removed (or would be, with --dry-run)", 2: "no such round, nothing published without --force, or usage" },
            json: "{ removed, kept, dryRun? }",
          },
        },
      },
    },
  },
  lab: {
    command: "lab", script: "lab", group: "lab", summary: "the design canvas for the site's own graphics: SVG scenes under .parity/lab served on the site's tokens, light and dark side by side, on the LAN, and as a throwaway route on the site's own theme; rendered to the files a page ships; removed when done",
    usage: "agentic-cms lab <new | serve | route | render | clean> …",
    subcommands: {
      new: {
        command: "lab new", summary: "writes a scene to start from, .parity/lab/<name>.svg, on the kit's own contracts: an icon on the 24 grid in currentColor (what Icon renders), a mark on the 64 grid, or a loop with the reduced-motion rule and one SMIL animation",
        usage: "agentic-cms lab new <name> [--kind icon|mark|loop] [--json]",
        positionals: [{ name: "name", required: true, help: "lowercase letters, digits and hyphens; also the prefix of the scene's ids and keyframe names" }],
        flags: { kind: { type: "string", default: "icon", choices: ["icon", "mark", "loop"], help: "the template" }, json: { type: "boolean", help: "print { scene, file, kind }" } },
        examples: ["agentic-cms lab new pipeline --kind icon", "agentic-cms lab new spin --kind loop"],
        exit: { 0: "written", 2: "a bad name, an unknown kind, or a scene that already exists" },
        json: "{ scene, file, kind }",
      },
      serve: {
        command: "lab serve", summary: "serves the lab: every scene under .parity/lab (and --scenes files or folders) on the tokens of src/app/globals.css — inline in a light and a dark box at its sizes and enlarged, as an <img> on both grounds, with a scrubber and a replay over its animations and a switch to its still (/scene/<name>?still=1) — reloading on every save; prints the loopback and the LAN URLs and runs until Ctrl-C",
        usage: "agentic-cms lab serve [--host 0.0.0.0] [--port 8001] [--scenes <file|dir>]… [--sizes 24,40,64]",
        flags: {
          host: { type: "string", default: "0.0.0.0", value: "<address>", help: "the interface to listen on (0.0.0.0: every one, so a phone on the LAN can open it; 127.0.0.1: this machine only)" },
          port: { type: "number", default: 8001, help: "the port" },
          scenes: { type: "string", multiple: true, value: "<file|dir>", help: "more scenes: an SVG file, or a folder walked for .svg files (public/images/home, say, to reopen what a page ships)" },
          sizes: { type: "string", value: "<px,px>", help: "the sizes every scene is also shown at, inline and as an <img> — the sizes it ships at (without it: 24, 40 and 64 for an icon-sized scene, up to 96 px wide, and none for a bigger one)" },
        },
        examples: ["agentic-cms lab serve", "agentic-cms lab serve --sizes 32,160                 # a mark at the sizes it ships", "agentic-cms lab serve --scenes public/images/home --scenes public/images/ui --sizes 20,32"],
        exit: { 0: "stopped", 2: "the port is taken, a --scenes path that does not exist, or usage" },
      },
      route: {
        command: "lab route", summary: "writes the throwaway route src/app/lab-demo/page.tsx from the kit's template: every scene under .parity/lab inline on the site's own grounds (the page and a white card to start; the site adds its surfaces) through the LabScenes component of agentic-cms/lab, with the procedure for the person looking at it; the second window beside `lab serve`, removed by `lab clean` and never merged (the SEO audit fails it)",
        usage: "agentic-cms lab route [--force] [--json]",
        flags: { force: { type: "boolean", help: "overwrite a route that is already there" }, json: { type: "boolean", help: "print { file, path }" } },
        examples: ["agentic-cms lab route                      # then pnpm dev and /lab-demo"],
        exit: { 0: "written", 2: "the route exists (pass --force), or usage" },
        json: "{ file, path }",
      },
      render: {
        command: "lab render", summary: "renders one scene to the file a page ships, by the extension of --out: .svg (the tokens resolved for one scheme, the animation kept), .webp/.png/.jpg (a still at --at), or with --animate a loop as an animated .webp (sharp, no ffmpeg), .webm or .mp4 (ffmpeg); a loop also writes its still beside it (the <picture> fallback, the poster) and a raster its source scene",
        usage: "agentic-cms lab render <scene> --out <file> [--at 0] [--animate] [--frames <n>] [--fps 30] [--duration <s>] [--scale 1] [--width <px>] [--scheme light|dark] [--reduced] [--background transparent|paper] [--lossy] [--no-poster] [--no-source] [--scenes <file|dir>]… [--url <base>] [--json]",
        positionals: [{ name: "scene", required: true, help: "a scene: its name under .parity/lab, or its path without .svg under a --scenes file or folder" }],
        flags: {
          out: { type: "string", value: "<file>", help: "the file to write; its extension picks the format" },
          at: { type: "number", default: 0, help: "the time of a still, and where a loop starts, in seconds" },
          animate: { type: "boolean", help: "a frame sequence over the scene's duration instead of a still (what .webm and .mp4 always are)" },
          frames: { type: "number", default: 0, help: "how many frames (default: the duration times --fps)" },
          fps: { type: "number", default: 30, help: "frames per second of a loop" },
          duration: { type: "number", default: 0, help: "one cycle in seconds (default: the scene's data-duration, else what its animations declare)" },
          scale: { type: "number", default: 1, help: "device pixels per CSS pixel of a raster (2 for a retina asset)" },
          width: { type: "number", default: 0, help: "the CSS width to render at (default: the scene's own)" },
          scheme: { type: "string", default: "light", choices: ["light", "dark"], help: "the scheme the tokens resolve in (a raster is one scheme; render twice for both)" },
          reduced: { type: "boolean", help: "render under prefers-reduced-motion: reduce — what such a reader gets" },
          background: { type: "string", default: "transparent", choices: ["transparent", "paper"], help: "the ground of a raster (.jpg is always on the paper)" },
          lossy: { type: "boolean", help: "lossy WebP (quality 82) instead of lossless" },
          "no-poster": { type: "boolean", help: "do not write the still of a loop beside it (<name>-still.webp or .svg)" },
          "no-source": { type: "boolean", help: "do not copy the scene beside a raster (<name>.svg)" },
          scenes: { type: "string", multiple: true, value: "<file|dir>", help: "more scenes, as for serve" },
          url: { type: "string", value: "<base>", help: "a running lab instead of one started for the render" },
          json: { type: "boolean", help: "print the report" },
        },
        examples: ["agentic-cms lab render pipeline --out src/config/icons/pipeline.svg && agentic-cms icons add file:pipeline", "agentic-cms lab render mark --out public/images/home/mark.svg --scheme dark", "agentic-cms lab render spin --out public/images/home/spin.webp --animate --fps 12    # the loop, its still beside it", "agentic-cms lab render hero --out public/images/home/hero.webm --animate --background paper"],
        exit: { 0: "written", 2: "an unknown scene, an extension the lab cannot write, no browser, no ffmpeg for .webm/.mp4 (or a transparent .webm with Playwright's bundled build, which writes VP8 on the paper only), or usage" },
        json: "{ scene, file, still, source, format, width, height, frames, fps, duration, scheme, background, bytes, note, console }",
      },
      clean: {
        command: "lab clean", summary: "removes .parity/lab (all but an icon round in progress, .parity/lab/rounds/<round>, which icons round retire removes) and the route src/app/lab-demo (when it is the kit's — one that imports agentic-cms/lab), and next dev's generated route types when they still name the route (the production build's type check reads them); what a render wrote under public/ (and src/config/icons/) is what stays", summary: "removes .parity/lab and the route src/app/lab-demo (when it is the kit's — one that imports agentic-cms/lab), and next dev's generated route types when they still name the route (the production build's type check reads them); what a render wrote under public/ (and src/config/icons/) is what stays",
        usage: "agentic-cms lab clean [--json]",
        flags: { json: { type: "boolean", help: "print { removed: [paths], kept: [paths] }" } },
        examples: ["agentic-cms lab clean"],
        exit: { 0: "removed, or nothing to remove" },
        json: "{ removed, kept }",
      },
    },
  },
  demo: {
    command: "demo", script: "demo", group: "demo", summary: "the design round's throwaway route: candidates for a section as real components in its frame with the page's real copy, lettered, the current version last — scaffolded from the registry and the page file, removed with the losing candidates",
    usage: "agentic-cms demo <new | clean> …",
    subcommands: {
      new: {
        command: "demo new", summary: "writes src/app/<name>-demo/page.tsx and one candidate per letter — a copy of the component beside it (<Name>A.tsx, <Name>B.tsx…) to edit into an idea; with --section the route reads the page's copy from its file on every render and shows every candidate in the section's real frame, with --component alone it renders each candidate with no props (a piece of the chrome, whose copy is the site's config); lettered with one line, inside the site's own layout, the current version last",
        usage: "agentic-cms demo new <name> <--section <type> | --component <file>> [--page <slug>] [--candidates 2] [--json]",
        positionals: [{ name: "name", required: true, help: "the route is src/app/<name>-demo; lowercase letters, digits and hyphens" }],
        flags: {
          section: { type: "string", value: "<type>", help: "the section type (a key of the registry, src/components/sections/render.tsx); the route then reads the page's copy and passes it to every candidate" },
          page: { type: "string", value: "<slug>", help: "the page file whose copy the route reads (default: the first under content/pages carrying the section); only with --section" },
          candidates: { type: "number", default: 2, help: "how many candidates, A onward (1 to 8)" },
          component: { type: "string", value: "<file>", help: "the component to copy: with --section, one outside the registry; alone, a piece of the chrome (a footer, a navbar, a button) whose candidates take no props" },
          json: { type: "boolean", help: "print the report" },
        },
        examples: ["agentic-cms demo new offers --section home-choose-us", "agentic-cms demo new band --section about-story --page sections-about --candidates 3", "agentic-cms demo new footer --component src/components/ui/Footer.tsx    # a piece of the chrome: no page copy, the candidates take no props"],
        exit: { 0: "written", 2: "neither --section nor --component, a bad name, a route or a candidate file that exists, a section the registry or no page carries, --page without --section, or usage" },
        json: "{ route, path, section, page, component, candidates: [{ letter, file }], data }",
      },
      clean: {
        command: "demo clean", summary: "removes the route (without a name, every route demo new wrote — a site's own *-demo folder is kept and named), every file the round created that nothing outside it imports — the candidates and whatever they alone use, found from the route's imports through new files only (the manifest demo new wrote, and git since the round began) — with their module.css, the round's assets (public/images/<name>-demo/) and next dev's generated route types while they still name the route (the production build's type check reads them); the component the candidates were copied from is never removed, and a new file something else imports (a piece the promoted section now uses) is kept and named",
        usage: "agentic-cms demo clean [name] [--dry-run] [--json]",
        positionals: [{ name: "name", help: "the demo's name; without one, every route demo new wrote (a site's own *-demo folder only by its name)" }],
        flags: { "dry-run": dryRun, json: { type: "boolean", help: "print { removed, kept } (and dryRun: true)" } },
        examples: ["agentic-cms demo clean offers", "agentic-cms demo clean offers --dry-run      # what would go, and what stays and why", "agentic-cms demo clean                     # every *-demo route"],
        exit: { 0: "removed, or nothing to remove" },
        json: "{ removed, kept, dryRun? }",
      },
    },
  },
};
