#!/usr/bin/env node
// Writes the command line's contract into docs/commands.md from the specs
// (scripts/lib/specs.mjs) — the same source the parser and `--help` read, so
// the docs cannot drift from the code. `--check` exits 1 when the file is
// stale (tools/hygiene.mjs and CI run it).
//
//   node tools/commands-doc.mjs            rewrites the block between the markers
//   node tools/commands-doc.mjs --check    exits 1 when it is out of date
import fs from "node:fs";
import path from "node:path";
import { flagValue } from "../scripts/lib/args.mjs";
import { SPECS } from "../scripts/lib/specs.mjs";

export const START = "<!-- commands-doc:start -->";
export const END = "<!-- commands-doc:end -->";
const FILE = path.resolve(import.meta.dirname, "../docs/commands.md");

const code = (s) => `\`${s}\``;
const sentence = (s) => s[0].toUpperCase() + s.slice(1) + ".";
const flagRow = ([name, flag]) => `| ${code(`--${name}${flag.type === "boolean" ? "" : ` ${flagValue(flag)}`}`)} | ${flag.help ?? ""}${flag.choices ? ` (one of ${flag.choices.map(code).join(", ")})` : ""}${flag.default !== undefined ? ` (default ${code(String(flag.default))})` : ""}${flag.multiple ? " (repeatable)" : ""} |`;

function leaf(spec, level) {
  const lines = [`${"#".repeat(level)} ${code(spec.command)}`, "", sentence(spec.summary), "", "```bash", spec.usage, "```", ""];
  const positionals = (spec.positionals ?? []).filter((p) => p.help);
  if (positionals.length) lines.push(...positionals.map((p) => `- ${code(`<${p.name}${p.variadic ? "..." : ""}>`)} — ${p.help}`), "");
  const flags = Object.entries(spec.flags ?? {});
  if (flags.length) lines.push("| flag | what |", "|---|---|", ...flags.map(flagRow), "");
  if (spec.exit) lines.push("Exit: " + Object.entries(spec.exit).map(([c, what]) => `${code(c)} ${what}`).join("; ") + ".", "");
  if (spec.json) lines.push(`${code("--json")} prints ${code(spec.json)}.`, "");
  if (spec.examples?.length) lines.push("```bash", ...spec.examples, "```", "");
  return lines;
}

const FAMILIES = ["content", "build gates", "images", "proof", "look & measure", "icons", "lab", "demo", "site"];

/** The Markdown block for every spec, by family: a section per command, a subsection per subcommand, the examples in a bash block. */
export function commandsMarkdown(specs) {
  const lines = [START, "<!-- generated by tools/commands-doc.mjs from scripts/lib/specs.mjs; do not edit by hand -->", ""];
  const byFamily = new Map(FAMILIES.map((f) => [f, []]));
  for (const spec of Object.values(specs)) { const g = spec.group ?? "other"; if (!byFamily.has(g)) byFamily.set(g, []); byFamily.get(g).push(spec); }
  for (const [family, members] of byFamily) {
    if (!members.length) continue;
    lines.push(`## ${family}`, "", `${members.map((m) => code(m.command)).join(" · ")}${members.some((m) => m.site) ? " — " + members.filter((m) => m.site).map((m) => code(m.command)).join(", ") + " read the site's registry and run in its root" : ""}`, "");
    for (const spec of members) lines.push(...section(spec));
  }
  lines.push(END);
  return lines.join("\n");
}

/** A command's section: a leaf, or a family heading and its subcommands one level down (a subcommand may be a family of its own). */
function section(spec, level = 3) {
  if (!spec.subcommands) return leaf(spec, level);
  return [`${"#".repeat(level)} ${code(spec.command)}`, "", sentence(spec.summary), "", "```bash", spec.usage, "```", "", ...Object.values(spec.subcommands).flatMap((sub) => section(sub, level + 1))];
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const current = fs.readFileSync(FILE, "utf8");
  const from = current.indexOf(START), to = current.indexOf(END);
  if (from === -1 || to === -1) { console.error(`commands-doc: ${path.relative(process.cwd(), FILE)} has no ${START} … ${END} markers`); process.exit(2); }
  const next = current.slice(0, from) + commandsMarkdown(SPECS) + current.slice(to + END.length);
  if (process.argv.includes("--check")) {
    if (next !== current) { console.error("commands-doc: docs/commands.md is out of date — run node tools/commands-doc.mjs and commit the result"); process.exit(1); }
    console.log("commands-doc: docs/commands.md is up to date");
  } else {
    fs.writeFileSync(FILE, next);
    console.log(`commands-doc: wrote ${Object.keys(SPECS).length} commands to docs/commands.md`);
  }
}
