#!/usr/bin/env node
// Writes the command line's contract into docs/commands.md from the specs
// (scripts/lib/specs.mjs) — the same source the parser and `--help` read, so
// the docs cannot drift from the code. `--check` exits 1 when the file is
// stale (tools/hygiene.mjs and CI run it).
//
//   node tools/commands-doc.mjs            rewrites the block between the markers
//   node tools/commands-doc.mjs --check    exits 1 when it is out of date
import fs from "node:fs";
import path from "node:path";
import { SPECS } from "../scripts/lib/specs.mjs";

export const START = "<!-- commands-doc:start -->";
export const END = "<!-- commands-doc:end -->";
const FILE = path.resolve(import.meta.dirname, "../docs/commands.md");

const code = (s) => `\`${s}\``;
const sentence = (s) => s[0].toUpperCase() + s.slice(1) + ".";
const flagRow = ([name, flag]) => `| ${code(`--${name}${flag.type === "boolean" ? "" : ` ${flag.value ?? "<n>"}`}`)} | ${flag.help ?? ""}${flag.default !== undefined ? ` (default ${code(String(flag.default))})` : ""}${flag.multiple ? " (repeatable)" : ""} |`;

function leaf(spec, level) {
  const lines = [`${"#".repeat(level)} ${code(spec.command)}`, "", sentence(spec.summary), "", "```bash", spec.usage, "```", ""];
  const positionals = (spec.positionals ?? []).filter((p) => p.help);
  if (positionals.length) lines.push(...positionals.map((p) => `- ${code(`<${p.name}${p.variadic ? "..." : ""}>`)} — ${p.help}`), "");
  const flags = Object.entries(spec.flags ?? {});
  if (flags.length) lines.push("| flag | what |", "|---|---|", ...flags.map(flagRow), "");
  if (spec.exit) lines.push("Exit: " + Object.entries(spec.exit).map(([c, what]) => `${code(c)} ${what}`).join("; ") + ".", "");
  if (spec.json) lines.push(`${code("--json")} prints ${code(spec.json)}.`, "");
  return lines;
}

/** The Markdown block for every spec: a section per command, a subsection per subcommand. */
export function commandsMarkdown(specs) {
  const lines = [START, "<!-- generated by tools/commands-doc.mjs from scripts/lib/specs.mjs; do not edit by hand -->", ""];
  for (const spec of Object.values(specs)) {
    if (!spec.subcommands) { lines.push(...leaf(spec, 3)); continue; }
    lines.push(`### ${code(spec.command)}`, "", sentence(spec.summary), "", "```bash", spec.usage, "```", "");
    for (const sub of Object.values(spec.subcommands)) lines.push(...leaf(sub, 4));
  }
  lines.push(END);
  return lines.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const current = fs.readFileSync(FILE, "utf8");
  const from = current.indexOf(START), to = current.indexOf(END);
  if (from === -1 || to === -1) { console.error(`commands-doc: ${path.relative(process.cwd(), FILE)} has no ${START} … ${END} markers`); process.exit(2); }
  const next = current.slice(0, from) + commandsMarkdown(SPECS) + current.slice(to + END.length);
  if (process.argv.includes("--check")) {
    if (next !== current) { console.error("commands-doc: docs/commands.md is out of date — run node tools/commands-doc.mjs and commit the result"); process.exit(1); }
    console.log("commands-doc: docs/commands.md is up to date");
  } else {
    fs.writeFileSync(FILE, next);
    console.log(`commands-doc: wrote ${Object.keys(SPECS).length} commands to docs/commands.md`);
  }
}
